---
# tasks file for ansible-role-mindboggle

- name: Install apt-get dependencies.
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - g++
  - git
  - make
  - libxt6
  - libgl1-mesa-glx

- name: Install conda python dependencies.
  sudo: False
  shell: "{{ miniconda_home }}/bin/conda install {{ item }} --yes -q executable=/bin/bash"
  with_items:
  - cmake 
  - vtk 
  - numpy 
  - scipy 
  - networkx 
  - traits 
  - nose
  - ipython-notebook
  - matplotlib

- name: Install nipype python package and dependencies.
  sudo: False
  shell: "{{ miniconda_home }}/bin/pip install -U {{ item }} executable=/bin/bash"
  with_items:
  - nibabel --use-mirrors
  - "https://github.com/trungdong/prov/archive/rdf.zip"
  - "https://github.com/nipy/nipype/archive/master.zip"
  - "https://github.com/RDFLib/rdflib/archive/master.zip"

- name: Set environment variables.
  sudo: False
  shell: "echo '{{ item }}' >> ~/.bashrc"
  with_items:
  - "export MINDBOGGLE_TOOLS={{ mindboggle_home }}/mindboggle_tools/bin/"
  - "export PATH=$PATH:$MINDBOGGLE_TOOLS"
  - "export DYLD_LIBRARY_PATH={{ miniconda_home }}/lib/vtk-5.10"

- name: Clone Mindboggle from Github.
  sudo: False
  git: repo=git://github.com/binarybottle/mindboggle.git
       dest={{ mindboggle_home }}

- name: Install Mindboggle Python software.
  sudo: False
  shell: "{{ miniconda_home }}/bin/pip install -U {{ mindboggle_home }} executable=/bin/bash"

- name: Compile Mindboggle C++ code with cmake.
  sudo: False
  shell: "{{ item }} chdir={{ mindboggle_home }}/mindboggle_tools/bin/ executable=/bin/bash"
  with_items:
  - "{{ miniconda_home }}/bin/cmake {{ mindboggle_home }}/mindboggle_tools"
  - make

- name: Create the dependency directories used for sync in vagrant.
  sudo: false
  file: path={{ item }} state=directory owner={{ ansible_ssh_user }}
  with_items:
  - /home/{{ ansible_ssh_user }}/freesurfer
  - /home/{{ ansible_ssh_user }}/ants
  - /home/{{ ansible_ssh_user }}/mindboggled
  - /home/{{ ansible_ssh_user }}/freesurfer_subjects
  - /home/{{ ansible_ssh_user }}/ants_subjects
  - /home/{{ ansible_ssh_user }}/atlases
  - /home/{{ ansible_ssh_user }}/dependencies

- name: Set Freesurfer and ANTs environment variables.
  sudo: False
  shell: "echo '{{ item }}' >> ~/.bashrc"
  with_items:
  - "export FREESURFER_HOME=/home/{{ ansible_ssh_user }}/freesurfer"
  - "source $FREESURFER_HOME/SetUpFreeSurfer.sh"
  - "export PATH=$PATH:/home/{{ ansible_ssh_user }}/ants"