---
# tasks file for ansible-role-mindboggle

- name: Install apt-get dependencies.
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - build-essential
  - git
  - make

- name: Install conda python dependencies.
  sudo: False
  shell: "{{ miniconda_home }}/bin/conda install {{ item }} --yes -q executable=/bin/bash"
  with_items:
  - cmake 
  - vtk 
  - numpy 
  - scipy 
  - networkx 
  - traits 
  - nose

- name: Install nipype python package and dependencies.
  sudo: False
  pip: name={{ item }} state=present executable={{ miniconda_home }}/bin/pip
  with_items:
  - nibabel
  - "git+https://github.com/trungdong/prov.git@rdf"
  - nipype

- name: Set environment variables.
  sudo: False
  command: echo "{{ item }}" >> ~/.bashrc
  with_items:
  - "export MINDBOGGLE_TOOLS={{ mindboggle_home }}/mindboggle_tools/bin/"
  - "export PATH=$PATH:$MINDBOGGLE_TOOLS"
#  - "export DYLD_LIBRARY_PATH={{ miniconda_home }}/lib/vtk-5.10:${DYLD_LIBRARY_PATH}"

- name: Clone Mindboggle from Github.
  sudo: False
  git: repo=git://github.com/binarybottle/mindboggle.git
       dest={{ mindboggle_home }}

- name: Install Mindboggle Python software.
  sudo: False
  pip: name={{ mindboggle_home }} state=present executable=/bin/bash

- name: Compile Mindboggle C++ code with cmake.
  sudo: False
  command: "{{ item }} chdir={{ mindboggle_home }}/mindboggle_tools/bin/ executable=/bin/bash"
  with_items:
  - cmake {{ mindboggle_home }}/mindboggle_tools
  - make    